export enum Category {
  OTHERS = 'others',
  HOME = 'home',
  HEALTH = 'health',
  TOYS = 'toys',
  GAMES = 'games',
  BOOKS = 'books',
  STATIONARY = 'stationary',
  FOOD = 'food',
  AUTOMOTIVE = 'automotive',
  MOBILE = 'Mobile',
  LAPTOP = 'Laptop',
  TABLET = 'Tablet',
  HEADPHONES = 'Headphones',
  TELEVISION = 'Television',
  CAMERA = 'Camera',
  SMARTWATCH = 'Smartwatch',
  MEN_CLOTHING = 'Men Clothing',
  WOMEN_CLOTHING = 'Women Clothing',
  KIDS_CLOTHING = 'Kids Clothing',
  FURNITURE = 'Furniture',
  KITCHEN_APPLIANCES = 'Kitchen Appliances',
  SKINCARE = 'Skincare',
  FITNESS_EQUIPMENT = 'Fitness Equipment',
  GROCERY = 'Grocery',
  PET_FOOD = 'Pet Food',
  JEWELRY = 'Jewelry',
}
